name: build-runner

on:
  push:
    branches:
    - master
    paths:
    - 'runner/**'
    - '.github/workflows/build-runner.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build container image
      run: make docker-build
      working-directory: runner
    - name: Docker Login
      run: docker login -u chenrui -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Push container image
      run: make docker-push
      working-directory: runner
